#!/bin/sh
/usr/sbin/sshd

# copied from https://github.com/docker-library/php/blob/master/8.2/bullseye/fpm/docker-php-entrypoint
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

php-fpm